# Generated by Django 5.0.1 on 2024-01-29 11:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_alter_product_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('locality', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=45)),
                ('mobile', models.IntegerField(default=0)),
                ('pincode', models.IntegerField()),
                ('state', models.CharField(choices=[('Maharashtra', 'Maharashtra'), ('Goa', 'Goa'), ('Telangana', 'Telangana'), ('Karnataka', 'Karnataka'), ('Tamil Nadu', 'Tamil Nadu'), ('Kerala', 'Kerala'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Gujarat', 'Gujarat'), ('Odisha', 'Odisha'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Chhattisgard', 'Chhattishgard'), ('Jharkhand', 'Jharkhand'), ('Bihar', 'Bihar'), ('Sikkim', 'Sikkim'), ('West Bengal', 'West Bengal'), ('Bihar', 'Bihar'), ('Assam', 'Assam'), ('Meghalaya', 'Meghalaya'), ('Tripura', 'Tripura'), ('Mizoram', 'Mizoram'), ('Manipur', 'Manipur'), ('Nagaland', 'Nagaland'), ('Arunchal Pradesh', 'Arunchal Pradesh'), ('Nagaland', 'Nagaland'), ('Rajasthan', 'Rajasthan'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Delhi', 'Delhi'), ('Haryana', 'Haryana'), ('Punjab', 'Punjab'), ('Uttarakhand', 'Uttarakhand'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Ladakh', 'Ladakh')], max_length=120)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
