# Generated by Django 5.0.1 on 2024-01-29 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='mobile',
            field=models.CharField(default=0, max_length=12),
        ),
    ]
