# Generated by Django 5.0.1 on 2024-02-01 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0008_payment_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='payemnt',
            new_name='payment',
        ),
    ]
